### ISSUE TITLE
解析包时出现问题

### ISSUE THREAD

**Issue by putianyi889** [hgraceb/FLopMinesweeper#1]
从雷网提供的二维码和项目主页提供的下载链接获得的两个apk均有此问题。
- https://flop.coding.net/p/Raw/d/Raw/git/raw/master/FlopMine/FlopMine.apk
- https://flop.coding.net/p/Raw/d/Raw/git/raw/master/FlopMine/APK/Release/FlopMine_1.0.0.200219_Release.apk

运行环境：
- 手机型号与版本号：华为EVA-AL10 8.0.0.540(C00patch02)
- EMUI版本：8.0.0
- Android版本：8.0.0

**Comment by hgraceb** [comment]
已修复（虽然看到得晚了点），重新下载即可，感谢反馈！
